apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app 
  labels:
    app: frontend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-app
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: something
        image: nvrbckdown/something        
       





